version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/recipes/*"
      - "/playground"
    schedule:
      interval: "weekly"
    groups:
      python-deps:
        patterns: ["*"]
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
